/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface CreateUserResult
 */
export interface CreateUserResult {
    /**
     * 
     * @type {User}
     * @memberof CreateUserResult
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof CreateUserResult
     */
    accessToken: string;
}

/**
 * Check if a given object implements the CreateUserResult interface.
 */
export function instanceOfCreateUserResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "accessToken" in value;

    return isInstance;
}

export function CreateUserResultFromJSON(json: any): CreateUserResult {
    return CreateUserResultFromJSONTyped(json, false);
}

export function CreateUserResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'accessToken': json['accessToken'],
    };
}

export function CreateUserResultToJSON(value?: CreateUserResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
        'accessToken': value.accessToken,
    };
}

