/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FiatCurrencyType
 */
export interface FiatCurrencyType {
    /**
     * 
     * @type {string}
     * @memberof FiatCurrencyType
     */
    name: string;
}

/**
 * Check if a given object implements the FiatCurrencyType interface.
 */
export function instanceOfFiatCurrencyType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function FiatCurrencyTypeFromJSON(json: any): FiatCurrencyType {
    return FiatCurrencyTypeFromJSONTyped(json, false);
}

export function FiatCurrencyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiatCurrencyType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function FiatCurrencyTypeToJSON(value?: FiatCurrencyType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

