/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FiatCurrencyTypeDTO
 */
export interface FiatCurrencyTypeDTO {
    /**
     * 
     * @type {string}
     * @memberof FiatCurrencyTypeDTO
     */
    name: string;
}

/**
 * Check if a given object implements the FiatCurrencyTypeDTO interface.
 */
export function instanceOfFiatCurrencyTypeDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function FiatCurrencyTypeDTOFromJSON(json: any): FiatCurrencyTypeDTO {
    return FiatCurrencyTypeDTOFromJSONTyped(json, false);
}

export function FiatCurrencyTypeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiatCurrencyTypeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function FiatCurrencyTypeDTOToJSON(value?: FiatCurrencyTypeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

