/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface LoginResult
 */
export interface LoginResult {
    /**
     * 
     * @type {User}
     * @memberof LoginResult
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof LoginResult
     */
    accessToken: string;
}

/**
 * Check if a given object implements the LoginResult interface.
 */
export function instanceOfLoginResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "accessToken" in value;

    return isInstance;
}

export function LoginResultFromJSON(json: any): LoginResult {
    return LoginResultFromJSONTyped(json, false);
}

export function LoginResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'accessToken': json['accessToken'],
    };
}

export function LoginResultToJSON(value?: LoginResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
        'accessToken': value.accessToken,
    };
}

