/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReauthenticateWithRefreshTokenResult
 */
export interface ReauthenticateWithRefreshTokenResult {
    /**
     * 
     * @type {number}
     * @memberof ReauthenticateWithRefreshTokenResult
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof ReauthenticateWithRefreshTokenResult
     */
    accessToken: string;
}

/**
 * Check if a given object implements the ReauthenticateWithRefreshTokenResult interface.
 */
export function instanceOfReauthenticateWithRefreshTokenResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "accessToken" in value;

    return isInstance;
}

export function ReauthenticateWithRefreshTokenResultFromJSON(json: any): ReauthenticateWithRefreshTokenResult {
    return ReauthenticateWithRefreshTokenResultFromJSONTyped(json, false);
}

export function ReauthenticateWithRefreshTokenResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReauthenticateWithRefreshTokenResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'accessToken': json['accessToken'],
    };
}

export function ReauthenticateWithRefreshTokenResultToJSON(value?: ReauthenticateWithRefreshTokenResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'accessToken': value.accessToken,
    };
}

