/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransactionDTO } from './TransactionDTO';
import {
    TransactionDTOFromJSON,
    TransactionDTOFromJSONTyped,
    TransactionDTOToJSON,
} from './TransactionDTO';

/**
 * 
 * @export
 * @interface TransactionDTOPaginationResult
 */
export interface TransactionDTOPaginationResult {
    /**
     * 
     * @type {Array<TransactionDTO>}
     * @memberof TransactionDTOPaginationResult
     */
    records: Array<TransactionDTO>;
    /**
     * 
     * @type {number}
     * @memberof TransactionDTOPaginationResult
     */
    totalRecordCount: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionDTOPaginationResult
     */
    currentPageIndex: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionDTOPaginationResult
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionDTOPaginationResult
     */
    readonly totalPages: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionDTOPaginationResult
     */
    readonly hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionDTOPaginationResult
     */
    readonly hasNextPage: boolean;
}

/**
 * Check if a given object implements the TransactionDTOPaginationResult interface.
 */
export function instanceOfTransactionDTOPaginationResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "records" in value;
    isInstance = isInstance && "totalRecordCount" in value;
    isInstance = isInstance && "currentPageIndex" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "hasPreviousPage" in value;
    isInstance = isInstance && "hasNextPage" in value;

    return isInstance;
}

export function TransactionDTOPaginationResultFromJSON(json: any): TransactionDTOPaginationResult {
    return TransactionDTOPaginationResultFromJSONTyped(json, false);
}

export function TransactionDTOPaginationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDTOPaginationResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'records': ((json['records'] as Array<any>).map(TransactionDTOFromJSON)),
        'totalRecordCount': json['totalRecordCount'],
        'currentPageIndex': json['currentPageIndex'],
        'pageSize': json['pageSize'],
        'totalPages': json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function TransactionDTOPaginationResultToJSON(value?: TransactionDTOPaginationResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'records': ((value.records as Array<any>).map(TransactionDTOToJSON)),
        'totalRecordCount': value.totalRecordCount,
        'currentPageIndex': value.currentPageIndex,
        'pageSize': value.pageSize,
    };
}

