/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FiatCurrencyTypeDTO,
} from '../models';
import {
    FiatCurrencyTypeDTOFromJSON,
    FiatCurrencyTypeDTOToJSON,
} from '../models';

/**
 * 
 */
export class FiatCurrenciesApi extends runtime.BaseAPI {

    /**
     */
    async getFiatCurrenciesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FiatCurrencyTypeDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/FiatCurrencies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FiatCurrencyTypeDTOFromJSON));
    }

    /**
     */
    async getFiatCurrencies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FiatCurrencyTypeDTO>> {
        const response = await this.getFiatCurrenciesRaw(initOverrides);
        return await response.value();
    }

}
